### ISSUE TITLE
Verisetini indirmek için sağladığınız linkten indirme yapma hakkında:

### ISSUE THREAD

**Issue by ottosman** [sezer-muhammed/Teknofest-Ulasimda-Yapay-Zeka-Veri-Seti#1]
Merhaba, sağladığınız link ile google drive dan bir zip birdseye zip dosyasını indrimeye çalışırken sürekli 33GB da error alıyorum ve indirme işlemim iptal oluyor. Tarafımdan kaynaklanmadığını düşünüyorum, indirme hızım ve tekrarlamalarım sonucunda bu kanıya vardım. Kontrol edip geri dönüş sağlarsanız sevinirim.

**Comment by sezer-muhammed** [comment]
Merhabalar, 

Google drive linkindeki sorunun farkındayım.

Veri setini kişisel hesabımdan paylaştığım için kota sınırına takılıyor gibi görünüyor.

En kısa zamanda dosyaları ufak zipler halinde ekleyerek sorunu çözmeye çalışacağım

**Comment by ottosman** [comment]
En kısa sürede bu open-source kaynağı tekrardan işlevsel hale getirmeniz dileğiyle. Teşekkürler.

**Comment by ottosman** [comment]
> Merhabalar,
> 
> Google drive linkindeki sorunun farkındayım.
> 
> Veri setini kişisel hesabımdan paylaştığım için kota sınırına takılıyor gibi görünüyor.
> 
> En kısa zamanda dosyaları ufak zipler halinde ekleyerek sorunu çözmeye çalışacağım

Tekrardan merhaba, verisetini güncellemenizi heyecan ile bekliyorum herhangi bir gelişme veya güncellemenize yardım edebileceğim bir husus var mı?

**Comment by sezer-muhammed** [comment]
> > Merhabalar,
> > Google drive linkindeki sorunun farkındayım.
> > Veri setini kişisel hesabımdan paylaştığım için kota sınırına takılıyor gibi görünüyor.
> > En kısa zamanda dosyaları ufak zipler halinde ekleyerek sorunu çözmeye çalışacağım
> 
> Tekrardan merhaba, verisetini güncellemenizi heyecan ile bekliyorum herhangi bir gelişme veya güncellemenize yardım edebileceğim bir husus var mı?

Merhabalar,

Teşekkür ederim,

Dataset'i düzenledim ve yolov8 HUB'a yüklüyorum ancak bağlantı hızım yavaş, zannımca yarın içerisinde linki güncellemiş olacağım

**Comment by ottosman** [comment]
Emekleriniz için teşekkürler, takipteyim.

**Comment by sezer-muhammed** [comment]
Merhaba,

Ultralytics hub'a 4 kere yükledim ancak sunucu hatası alıyorum, yeni bir drive linki paylaşacağım umarım çalışır

**Comment by ottosman** [comment]
Anladım, umarım düzelir. Kolay gelsin

**Comment by ottosman** [comment]
Farklı platforma koyduğunuzda burada da link olarak paylaşırsanız çok sevinirim.

**Comment by sezer-muhammed** [comment]
@ottosman Bu linki dener ve başarılı olursa haber verir misiniz?

https://drive.google.com/file/d/1-7rqzSOsMBMdx4_Fsp5bkctpH4GqPlaN/view?usp=sharing

**Comment by ottosman** [comment]
Maalesef 4 kez indrimeyi denedim ancak belirli bir yüzdeden sonra yine başarısız sonuç alıyorum.

**Comment by emirelcuk** [comment]
Ben indirmede sorun yaşamadım bu arada

> Maalesef 4 kez indrimeyi denedim ancak belirli bir yüzdeden sonra yine başarısız sonuç alıyorum.

**Comment by ottosman** [comment]
> Ben indirmede sorun yaşamadım bu arada
> 
> > Maalesef 4 kez indrimeyi denedim ancak belirli bir yüzdeden sonra yine başarısız sonuç alıyorum.
> 
> 

Windows 10 pc ile 5Mbps internet eşliğinde 8 indirme denemesinde bulundum. Mozilla Firefox kullaniyorum ancak yine de başaramadım.

**Comment by ottosman** [comment]
Güncel olarak  farklı pcler ve microsoft edge ile de denedim ancak ilk başta karşılaştığımız "birçok kişi tarafından indirildi" sorununu tekrar aldım.

**Comment by sezer-muhammed** [comment]
Yolohub'a yüksek hızlı bir yerden yüklemeye çalışacağım bugün umarım
O da olmazsa önerebileceğiniz platformlar var mıdır?

**Comment by ottosman** [comment]
> Yolohub'a yüksek hızlı bir yerden yüklemeye çalışacağım bugün umarım
> O da olmazsa önerebileceğiniz platformlar var mıdır?

We transfer, Cloud Mailru, Dropbox ve Mediafire. Özellikle Wetransfer sitesini bireysel olarak da kullanmaktayım büyük veri aktarımlarinda. Son olarak eğer serverlarınızda yeterli alan var ise WinSCP gibi programlar ile sitenin alt dosylarina koyarak hem kurumsalliğınızı hem de ulaşılabilirliğinizi artırmış olabilirsiniz. Sevgilerle.

**Comment by sezer-muhammed** [comment]
Teşekkürler,

Ancak kurumsal bir veriseti değil. Şevval'le bizim bireysel bir paylaşımımız o sebeple kişisel Drive'ımdan veya maliyetsiz platformlardan paylaşmak zorundayım ki uzun zamanlar veriseti durabilsin.

**Comment by ottosman** [comment]
Tekrardan merhaba, herhangi bir gelişme var mı?

**Comment by kadirnar** [comment]
@sezer-muhammed 

HuggingFace platformuna yüklemeyi deneyebilirsin. Yanlış hatırlamıyorsam 50GB depolama alanını ücretsiz veriyor.

**Comment by sezer-muhammed** [comment]
> @sezer-muhammed
> 
> HuggingFace platformuna yüklemeyi deneyebilirsin. Yanlış hatırlamıyorsam 50GB depolama alanını ücretsiz veriyor.

Yolohub da 100gb veriyor, 5 kere oraya yüklemeyi denedim ama internetim gitgelli kopunca sıfırlanıyor, bir de veri seti 54GB

huggingface için parçalama veya boyutta azaltmaya gitmek gerekebilir ancak onları da çok yapmak istemiyorum çünkü indirip yüklemem başlı başına sorun

**Comment by ottosman** [comment]
O zaman maalesef bu verisetine erişim sağlayamayacağız, üzücü. Yine de topluluğa katkılarınız için teşekkürler.

**Comment by sezer-muhammed** [comment]
> O zaman maalesef bu verisetine erişim sağlayamayacağız, üzücü. Yine de topluluğa katkılarınız için teşekkürler.

dataset'i tekrar düzenleyip yolohub'a yükleyeceğim, ancak zaman alabilir

**Comment by ottosman** [comment]
Anladım. Sabırsızlıkla bekliyorum.

**Comment by Berat8777** [comment]
Veri setinizde kaç tane sınıf kullandınız ve bu sınıflar nelerdir öğrenebilir miyim?

**Comment by HarunHarmann** [comment]
> Veri setinizde kaç tane sınıf kullandınız ve bu sınıflar nelerdir öğrenebilir miyim?

25 adet sınıf var sanırım ve şu şekilde:
yuap
kam
yaya
uuap
car
bis
motor
ismak
bus
uyam
w
ins
1
2
mo
yaam
3
arac
4
insan
yaup
5
mot
tasit
tren

Fakat çoğu anlaşılır değil o yüzden nasıl elimine ederiz bilmiyorum. Mesela sayılar neyi ifade ediyor? Motor var, mot var, mo var, bunların hepsi motor mu? Gibi sorular doğuyor :)

**Comment by sezer-muhammed** [comment]
> > Veri setinizde kaç tane sınıf kullandınız ve bu sınıflar nelerdir öğrenebilir miyim?
> 
> 25 adet sınıf var sanırım ve şu şekilde: yuap kam yaya uuap car bis motor ismak bus uyam w ins 1 2 mo yaam 3 arac 4 insan yaup 5 mot tasit tren
> 
> Fakat çoğu anlaşılır değil o yüzden nasıl elimine ederiz bilmiyorum. Mesela sayılar neyi ifade ediyor? Motor var, mot var, mo var, bunların hepsi motor mu? Gibi sorular doğuyor :)

Haklısınız, dataset'i temizlemiştim ancak bir karışıklık sebebiyle yükleyemedim. Toplamda 11 sınıf var.

1, 2, 3, 4, 5 etiketleri diğer dataset'lerden geliyor. 1, 2, 4, 5 araç 3 ise insan demek.

Datalar elle etiketlendi mot, mo gibi durumlar insan hatası hepsi motor demek.

Biz temizlerken bütün labellardan bir görseli kaydedip onun ne olduğuna kendimiz bakarak temizlemiştik, ancak şu an işlerimiz sebebiyle tekrar zaman ayıramıyoruz. Bu dataset Opensource bir dataset, isteyen herhangi birisi düzeltip pull request atabilir seve seve düzenleriz.

**Comment by HarunHarmann** [comment]
> > > Veri setinizde kaç tane sınıf kullandınız ve bu sınıflar nelerdir öğrenebilir miyim?
> > 
> > 
> > 25 adet sınıf var sanırım ve şu şekilde: yuap kam yaya uuap car bis motor ismak bus uyam w ins 1 2 mo yaam 3 arac 4 insan yaup 5 mot tasit tren
> > Fakat çoğu anlaşılır değil o yüzden nasıl elimine ederiz bilmiyorum. Mesela sayılar neyi ifade ediyor? Motor var, mot var, mo var, bunların hepsi motor mu? Gibi sorular doğuyor :)
> 
> Haklısınız, dataset'i temizlemiştim ancak bir karışıklık sebebiyle yükleyemedim. Toplamda 11 sınıf var.
> 
> 1, 2, 3, 4, 5 etiketleri diğer dataset'lerden geliyor. 1, 2, 4, 5 araç 3 ise insan demek.
> 
> Datalar elle etiketlendi mot, mo gibi durumlar insan hatası hepsi motor demek.
> 
> Biz temizlerken bütün labellardan bir görseli kaydedip onun ne olduğuna kendimiz bakarak temizlemiştik, ancak şu an işlerimiz sebebiyle tekrar zaman ayıramıyoruz. Bu dataset Opensource bir dataset, isteyen herhangi birisi düzeltip pull request atabilir seve seve düzenleriz.

Cevabınız için çok teşekkürler, bu arada dataset paylaşımı için de gerçekten teşekkürler, çok yardımcı oldu. Verdiğiniz bilgilerle düzeltip daha sonra request atarım diye düşünüyorum. İyi çalışmalar :)

**Comment by ottosman** [comment]
> > > > Veri setinizde kaç tane sınıf kullandınız ve bu sınıflar nelerdir öğrenebilir miyim?
> > > 
> > > 
> > > 25 adet sınıf var sanırım ve şu şekilde: yuap kam yaya uuap car bis motor ismak bus uyam w ins 1 2 mo yaam 3 arac 4 insan yaup 5 mot tasit tren
> > > Fakat çoğu anlaşılır değil o yüzden nasıl elimine ederiz bilmiyorum. Mesela sayılar neyi ifade ediyor? Motor var, mot var, mo var, bunların hepsi motor mu? Gibi sorular doğuyor :)
> > 
> > Haklısınız, dataset'i temizlemiştim ancak bir karışıklık sebebiyle yükleyemedim. Toplamda 11 sınıf var.
> > 
> > 1, 2, 3, 4, 5 etiketleri diğer dataset'lerden geliyor. 1, 2, 4, 5 araç 3 ise insan demek.
> > 
> > Datalar elle etiketlendi mot, mo gibi durumlar insan hatası hepsi motor demek.
> > 
> > Biz temizlerken bütün labellardan bir görseli kaydedip onun ne olduğuna kendimiz bakarak temizlemiştik, ancak şu an işlerimiz sebebiyle tekrar zaman ayıramıyoruz. Bu dataset Opensource bir dataset, isteyen herhangi birisi düzeltip pull request atabilir seve seve düzenleriz.
> 
> Cevabınız için çok teşekkürler, bu arada dataset paylaşımı için de gerçekten teşekkürler, çok yardımcı oldu. Verdiğiniz bilgilerle düzeltip daha sonra request atarım diye düşünüyorum. İyi çalışmalar :) 

Siz verisetini indirebildiniz mi?

**Comment by HarunHarmann** [comment]
> > > > > Veri setinizde kaç tane sınıf kullandınız ve bu sınıflar nelerdir öğrenebilir miyim?
> > > > 
> > > > 
> > > > 25 adet sınıf var sanırım ve şu şekilde: yuap kam yaya uuap car bis motor ismak bus uyam w ins 1 2 mo yaam 3 arac 4 insan yaup 5 mot tasit tren
> > > > Fakat çoğu anlaşılır değil o yüzden nasıl elimine ederiz bilmiyorum. Mesela sayılar neyi ifade ediyor? Motor var, mot var, mo var, bunların hepsi motor mu? Gibi sorular doğuyor :)
> > > 
> > > 
> > > Haklısınız, dataset'i temizlemiştim ancak bir karışıklık sebebiyle yükleyemedim. Toplamda 11 sınıf var.
> > > 1, 2, 3, 4, 5 etiketleri diğer dataset'lerden geliyor. 1, 2, 4, 5 araç 3 ise insan demek.
> > > Datalar elle etiketlendi mot, mo gibi durumlar insan hatası hepsi motor demek.
> > > Biz temizlerken bütün labellardan bir görseli kaydedip onun ne olduğuna kendimiz bakarak temizlemiştik, ancak şu an işlerimiz sebebiyle tekrar zaman ayıramıyoruz. Bu dataset Opensource bir dataset, isteyen herhangi birisi düzeltip pull request atabilir seve seve düzenleriz.
> > 
> > 
> > Cevabınız için çok teşekkürler, bu arada dataset paylaşımı için de gerçekten teşekkürler, çok yardımcı oldu. Verdiğiniz bilgilerle düzeltip daha sonra request atarım diye düşünüyorum. İyi çalışmalar :)
> 
> Siz verisetini indirebildiniz mi?


Evet, drive linki üzerinden indirdim.
