### ISSUE TITLE
Etiketleme Hakkında

### ISSUE THREAD

**Issue by Emrecangok** [sezer-muhammed/Teknofest-Ulasimda-Yapay-Zeka-Veri-Seti#2]
ReadMe kısmında yoloda etiketlemenin txt dosyaları şeklinde yapıldığını söylemişsiniz ancak dosyalarda xml biçiminde. Derin Öğrenmede yeniyim bilgilendirirseniz sevinirim, teşekkürler.

**Comment by beratersari** [comment]
Veri seti ile ilgi paylaşılan fotoğraf ile veri setindeki classlar uyuşmuyor. Dağınık haldeki bir veri setini temizlemek yeni bir veri etiketlemek kadar zaman alır. Modeli eğittikleri veriyi paylaşmamışlar gibi. Güzel bir şey düşünülmüş fakat keşke preprocess ettikleri halini paylaşsalarmış.
